[tool.black]
line-length = 100
include = '(mypy_boto3_builder|tests)/.*\.pyi?$'
target-version = [
    'py36',
    'py37',
    'py38',
]

[tool.isort]
profile = "black"
line_length = 100
known_first_party = [
    "mypy_boto3_builder",
    "tests",
]
src_paths = []
