name: Code style and test
concurrency:
  group: on_push
  cancel-in-progress: true

on:
  push:
    paths-ignore:
      - pyproject.toml
      - setup.cfg
      - CHANGELOG.md
  workflow_dispatch: {}

jobs:
  unit-tests:
    name: Code style & unit tests
    runs-on: ubuntu-latest
    env:
      PIP_NO_CACHE_DIR: false
      PIP_USER: 1
      PYTHONUSERBASE: ${{ github.workspace }}/.cache/py-user-base
    steps:
      - name: Add PYTHONUSERBASE to PATH
        id: add-pythonuserbase
        run: |
          echo '${{ env.PYTHONUSERBASE }}/bin/' >> $GITHUB_PATH
      - uses: actions/checkout@v2
      - name: Set up Python
        id: python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Cache packages
        id: cache
        uses: actions/cache@v2
        with:
          path: ${{ env.PYTHONUSERBASE }}
          key: ${{ steps.python.outputs.python-version }}-full-${{ secrets.CACHE_KEY }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ steps.python.outputs.python-version }}-full-${{ secrets.CACHE_KEY }}-
      - name: Install poetry
        run: |
          python -m pip install -U poetry pip wheel aiobotocore
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          poetry config virtualenvs.create false
          poetry install -n
          python -m pip install -U boto3-stubs botocore-stubs
      - name: Install Node.js dependencies
        run: |
          npm install -g pyright
      - name: Lint
        run: |
          python -m flake8 mypy_boto3_builder
          npx pyright mypy_boto3_builder
          python -m mypy mypy_boto3_builder
          python -m black --check mypy_boto3_builder tests
          python -m isort -c mypy_boto3_builder tests
      - name: Test
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          python -m pytest

  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    env:
      PIP_NO_CACHE_DIR: false
      PIP_USER: 1
      PYTHONUSERBASE: ${{ github.workspace }}/.cache/py-user-base
    steps:
      - name: Add PYTHONUSERBASE to PATH
        id: add-pythonuserbase
        run: |
          echo '${{ env.PYTHONUSERBASE }}/bin/' >> $GITHUB_PATH
      - uses: actions/checkout@v2
      - name: Set up Python
        id: python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Cache packages
        uses: actions/cache@v2
        id: cache
        with:
          path: ${{ env.PYTHONUSERBASE }}
          key: ${{ steps.python.outputs.python-version }}-full-${{ secrets.CACHE_KEY }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ steps.python.outputs.python-version }}-full-${{ secrets.CACHE_KEY }}-
      - name: Install poetry
        run: |
          python -m pip install -U poetry pip wheel aiobotocore
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          poetry config virtualenvs.create false
          poetry install -n
          python -m pip install -U boto3-stubs botocore-stubs
      - name: Install Node.js dependencies
        run: |
          npm install -g pyright
      - name: Install builder
        run: |
          python -m pip install .
      - name: Integration tests
        run: |
          python scripts/integration.py
