name: Send coverage report

on:
  push:
    branches:
      - main
    paths:
      - mypy_boto3_builder/**
      - tests/**
  workflow_dispatch: {}

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Set up Python
        id: python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: "poetry"
      - name: Install dependencies
        run: |
          poetry install -n
          poetry run pip install -U aiobotocore
          poetry install -n
      - name: Send coverage report
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          poetry run pytest --cov-report term --cov mypy_boto3_builder
          poetry run codecov
