name: Code style and test
concurrency:
  group: on_push
  cancel-in-progress: true

on:
  push:
    paths-ignore:
      - pyproject.toml
      - setup.cfg
      - CHANGELOG.md
  workflow_dispatch: {}

jobs:
  unit-tests:
    name: Code style & unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python
        id: python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: "poetry"
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install -n
          poetry run pip install -U aiobotocore
      - name: Install Node.js dependencies
        run: |
          npm install -g pyright
      - name: Lint
        run: |
          poetry run flake8 mypy_boto3_builder
          npx pyright mypy_boto3_builder
          poetry run mypy mypy_boto3_builder
          poetry run black --check mypy_boto3_builder tests
          poetry run isort -c mypy_boto3_builder tests
      - name: Test
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          poetry run pytest

  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python
        id: python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: "poetry"
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install -n
          poetry run pip install -U aiobotocore
      - name: Install Node.js dependencies
        run: |
          npm install -g pyright
      - name: Integration tests
        run: |
          poetry run python scripts/integration.py
