name: Send coverage report

on:
  push:
    branches:
      - master
    paths:
      - mypy_boto3_builder/**
      - tests/**
  workflow_dispatch: {}

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    env:
      PIP_NO_CACHE_DIR: false
      PIP_USER: 1
      PYTHONUSERBASE: ${{ github.workspace }}/.cache/py-user-base
    steps:
      - name: Add PYTHONUSERBASE to PATH
        id: add-pythonuserbase
        run: |
          echo '${{ env.PYTHONUSERBASE }}/bin/' >> $GITHUB_PATH
      - uses: actions/checkout@v2
      - name: Set up Python
        id: python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Cache packages
        id: cache
        uses: actions/cache@v2
        with:
          path: ${{ env.PYTHONUSERBASE }}
          key: ${{ steps.python.outputs.python-version }}-full-${{ secrets.CACHE_KEY }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ steps.python.outputs.python-version }}-full-${{ secrets.CACHE_KEY }}-
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          python -m pip install -U poetry pip wheel
          poetry config virtualenvs.create false
          poetry install -n
          python -m pip install -U boto3-stubs botocore-stubs
      - name: Send coverage report
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          python -m pytest --cov-report term --cov mypy_boto3_builder
          python -m codecov
