name: Code style and test

on:
  push:
    paths-ignore:
      - pyproject.toml
      - setup.cfg
      - CHANGELOG.md

jobs:
  unit-tests:
    name: Code style & unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Cache packages
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.venv
          key: 3.9-full-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            3.9-full-
      - name: Install dependencies
        run: |
          python -m pip install -U poetry pip wheel
          python -m poetry install -n
      - name: Lint
        run: |
          python -m flake8 mypy_boto3_builder
          python -m mypy mypy_boto3_builder
      - name: Test
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          python -m pytest

  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Cache packages
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.venv
          key: 3.9-full-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            3.9-full-
      - name: Install dependencies
        run: |
          python -m pip install -U poetry pip wheel
          python -m poetry install -n
      - name: Integration tests
        run: |
          scripts/integration.sh
