name: Send coverage report

on:
  push:
    branches:
      - master
    paths:
      - mypy_boto3_builder/**
      - tests/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: Cache packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: 3.8-package-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            3.8-package-
      - name: Install dependencies
        run: |
          python -m pip install -U poetry pip wheel
          python -m poetry config virtualenvs.create false
          python -m poetry install -n
      - name: Send coverage report
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          pytest --cov-report term --cov mypy_boto3_builder
          codecov
