name: Send coverage report

on:
  push:
    branches:
      - master
    paths:
      - mypy_boto3_builder/**
      - tests/**

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Cache packages
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.venv
          key: 3.9-full-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            3.9-full-
      - name: Install dependencies
        run: |
          python -m pip install -U poetry pip wheel
          python -m poetry install -n
      - name: Send coverage report
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          python -m pytest --cov-report term --cov mypy_boto3_builder
          python -m codecov
