name: Bump version and dockerize

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: Version for publishing
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install latest boto3
        run: |
          python -m pip install -U boto3 botocore
      - name: Get version
        id: version
        uses: actions/github-script@v4
        with:
          script: |
            if (context.payload.inputs && context.payload.inputs.version) {
              return context.payload.inputs.version
            }
            return context.ref.split('/').pop()
      - name: Install builder
        run: |
          python -m pip install -U poetry pip wheel
          poetry config virtualenvs.create false
          poetry install -n
      - name: Bump version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.version.outputs.result }}
        run: |
          scripts/bump_version.sh
      - name: Dockerize
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          scripts/dockerize.sh
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          poetry build
          twine upload  --non-interactive dist/*
