name: Bump version and dockerize

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: Version for publishing
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install latest boto3
        run: |
          python -m pip install -U boto3 botocore
      - name: Get version
        id: version
        uses: actions/github-script@v4
        with:
          script: |
            if (context.payload.inputs && context.payload.inputs.version) {
              return context.payload.inputs.version
            }
            return context.ref.split('/').pop()
      - name: Extract variables from env
        id: vars
        run: |
          VERSION=${{ steps.version.outputs.result }}
          echo "Version ${VERSION}"
          BOTO3_VERSION=$(python -c 'import boto3; print(boto3.__version__)')
          BOTOCORE_VERSION=$(python -c 'import botocore; print(botocore.__version__)')
          LAST_PACKAGE_VERSION=$(curl https://pypi.org/pypi/boto3-stubs/json | jq -r '.releases|keys[]' | grep -F "${BOTO3_VERSION}." | sort -k 4,4 -t '.' | tail -1)
          LAST_BOTO3_VERSION=`echo "${PACKAGE_VERSION}" | awk 'BEGIN{FS=OFS="."}{print$1, $2, $3;}'`
          if [ -z ${LAST_PACKAGE_VERSION} ]; then
            PACKAGE_VERSION="${BOTO3_VERSION}.0"
            echo No builds found, preparing initial ${PACKAGE_VERSION}
          else
            PACKAGE_VERSION=`echo "${LAST_PACKAGE_VERSION}" | awk 'BEGIN{FS=OFS="."}{$4=$4+1; print $0;}'`
            echo Version ${LAST_PACKAGE_VERSION} found, increasing to ${PACKAGE_VERSION}
          fi

          echo Boto3 version: ${BOTO3_VERSION}
          echo Botocore version: ${BOTOCORE_VERSION}
          echo Builder version: ${VERSION}
          echo Last package version: ${LAST_PACKAGE_VERSION}
          echo Build package version: ${PACKAGE_VERSION}

          echo "##[set-output name=build_version;]$(echo ${PACKAGE_VERSION})"
          echo "##[set-output name=version;]$(echo ${VERSION})"
      - name: Install builder
        run: |
          python -m pip install -U poetry pip wheel
          poetry config virtualenvs.create false
          poetry install -n
      - name: Install unreleased boto3 stubs
        env:
          BUILD_VERSION: ${{ steps.vars.outputs.build_version }}
        run: |
          ./scripts/build.sh --skip-services -b $BUILD_VERSION
          ./scripts/install.sh master
      - name: Bump version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.vars.outputs.version }}
        run: |
          scripts/bump_version.sh
          poetry install -n
          poetry shell
      - name: Integration tests
        run: |
          scripts/integration.sh
      - name: Dockerize
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          scripts/dockerize.sh
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          poetry build
          twine upload  --non-interactive dist/*
      - name: Build packages
        env:
          BUILD_VERSION: ${{ steps.vars.outputs.build_version }}
        run: |
          rm -rf mypy_boto3_output/*
          scripts/build.sh --panic -b $BUILD_VERSION
      - name: Install dependencies for publishing
        run: |
          python -m pip install setuptools wheel twine
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          scripts/release.sh
