name: Sanity check

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      boto3_version:
        description: Target boto3 version

jobs:
  publish-boto3-stubs:
    env:
      PIP_NO_CACHE_DIR: false
      PIP_USER: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extract versions
        id: vars
        uses: actions/github-script@v4
        with:
          script: |
            const { getBoto3Version, getBotocoreVersion } = require('./.github/workflows/helpers.js')

            const boto3Version = (context.payload.inputs && context.payload.inputs.boto3_version) ? context.payload.inputs.boto3_version : await getBoto3Version()
            const botocoreVersion = getBotocoreVersion(boto3Version)
            core.info(`Boto3 version ${boto3Version}`)
            core.info(`Botocore version ${botocoreVersion}`)
            core.setOutput('version', boto3Version)
            core.setOutput('boto3-version', boto3Version)
            core.setOutput('botocore-version', botocoreVersion)
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install boto3
        env:
          BOTO3_VERSION: ${{ steps.vars.outputs.boto3-version }}
          BOTOCORE_VERSION: ${{ steps.vars.outputs.botocore-version }}
        run: |
          python -m pip install -U boto3==${BOTO3_VERSION} botocore==${BOTOCORE_VERSION}
      - name: Install dependencies
        run: |
          python -m pip install -U poetry pip wheel
          poetry config virtualenvs.create false
          poetry install -n
          sudo npm install -g pyright
      - name: Build packages
        env:
          VERSION: ${{ steps.vars.outputs.version }}
        run: |
          rm -rf mypy_boto3_output/*
          python -m mypy_boto3_builder mypy_boto3_output -b $VERSION
      - name: Install master packages
        run: |
          ./scripts/install.sh master
      - name: Check output
        run: |
          python ./scripts/check_output.py -p ./mypy_boto3_output
